# Generated by Django 4.2.7 on 2025-12-11 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('STAGIAIRE', 'Stagiaire'), ('ENTREPRISE', 'Entreprise'), ('ADMIN', 'Administrateur')], max_length=20, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('niveau_etude', models.CharField(blank=True, max_length=100, verbose_name="Niveau d'études")),
                ('domaine', models.CharField(blank=True, max_length=100, verbose_name="Domaine d'études")),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='CV (PDF)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stagiaire_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stagiaire',
                'verbose_name_plural': 'Stagiaires',
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('secteur_activite', models.CharField(max_length=100, verbose_name="Secteur d'activité")),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('description', models.TextField(blank=True, verbose_name="Description de l'entreprise")),
                ('contact_nom', models.CharField(max_length=100, verbose_name='Nom du contact')),
                ('contact_prenom', models.CharField(max_length=100, verbose_name='Prénom du contact')),
                ('contact_fonction', models.CharField(blank=True, max_length=100, verbose_name='Fonction du contact')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
    ]
