# Generated by Django 4.2.27 on 2025-12-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('NOUVELLE_CANDIDATURE', 'Nouvelle candidature'), ('CANDIDATURE_ACCEPTEE', 'Candidature acceptée'), ('CANDIDATURE_REFUSEE', 'Candidature refusée'), ('OFFRE_VALIDEE', 'Offre validée'), ('OFFRE_REFUSEE', 'Offre refusée'), ('NOUVEAU_STAGIAIRE', 'Nouveau stagiaire inscrit')], max_length=50, verbose_name='Type de notification'),
        ),
    ]
