# Generated by Django 4.2.7 on 2025-12-12 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du stage')),
                ('type_stage', models.CharField(choices=[('OBSERVATION', "Stage d'observation"), ('INITIATION', "Stage d'initiation"), ('PERFECTIONNEMENT', 'Stage de perfectionnement'), ('PFE', "Projet de fin d'études")], max_length=20, verbose_name='Type de stage')),
                ('domaine', models.CharField(max_length=100, verbose_name='Domaine')),
                ('description', models.TextField(verbose_name='Description')),
                ('competences_requises', models.TextField(help_text='Séparées par des virgules', verbose_name='Compétences requises')),
                ('duree', models.CharField(max_length=50, verbose_name='Durée')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('remuneration', models.CharField(blank=True, max_length=100, verbose_name='Rémunération')),
                ('nombre_places', models.IntegerField(default=1, verbose_name='Nombre de places')),
                ('est_active', models.BooleanField(default=True, verbose_name='Offre active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_limite', models.DateField(blank=True, null=True, verbose_name='Date limite de candidature')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='accounts.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Offre de stage',
                'verbose_name_plural': 'Offres de stage',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettre_motivation', models.TextField(blank=True, verbose_name='Lettre de motivation')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_candidature', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='stages.offrestage', verbose_name='Offre')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='accounts.stagiaire', verbose_name='Stagiaire')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-date_candidature'],
                'unique_together': {('offre', 'stagiaire')},
            },
        ),
    ]
