# Generated by Django 4.2.27 on 2025-12-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_offrestage_date_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offrestage',
            name='date_fin',
        ),
    ]
